name: publish

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: mskelton/setup-yarn@v1
      - run: yarn build
      - uses: actions/upload-pages-artifact@v1
        with:
          path: "./build"
      - uses: actions/deploy-pages@v1
        id: deployment
